module.exports = {
  en: {
    onlineConsul: 'Counseling is carried out online using any means convenient to you. Online consulting allows you to quickly solve your problem directly on your computer, while there is no difference in what place you are and, accordingly, there is no time and risk for you to visit a specialist.',
    helpConfig: 'Having studied the need and taking into account the specifics of your business, we can give you valuable recommendations on choosing and implementing a 1C configuration. We can also help you with the integration of 1C configurations and third-party software. The right choice of software and hardware configuration will allow you to get rid of unnecessary unnecessary expenses and optimally build an automation plan.',
    implementSelectedSolutions: 'Help with a roadmap for implementation. For complex projects, we develop a project plan for the implementation and refinement of configurations. Projects thought out at the very beginning have a great chance of successful completion and are easy to operate.',
    ourConsultation: 'Our consultations and training will not pass without a trace for your employees. Depending on the need, we can provide one-time consultations for individual employees, as well as comprehensive training for a group of employees with an individual program. As a result, your employees gain knowledge and motivation.',
    ProperlySelected: 'The result of working with our company is the right software that is fully consistent with the goals. As a result, working with him will bring you comfort and joy. Our knowledge will help you avoid frequent mistakes that may occur when there is a lack of necessary implementation experience.',
    DesignedDesignDocumentation: 'Correctly executed project documentation is necessary to record the result of work on the implementation of software and “lessons learned” learned in the implementation of complex projects. Documentation is required at all stages of the project and software life cycle. For small projects, instructions are enough, but having them is highly desirable.',
    connect: 'Connect and work in “1C” via the Internet.',
    renting1: 'Automatically back up your data daily without the need for process tracking. You don’t have to worry about data loss. We guarantee prompt data recovery from archival copies.',
    renting2: 'Updating standard configurations in automatic mode at no additional cost. There is no need to look for specialists for updating and maintenance. Maintenance and completion will be even faster and easier.',
    renting3: 'Data is protected by professionals in accordance with the highest requirements in the field of information security. The servers on which the information is located are properly protected and specialized.'
  },
  ru: {
    onlineConsul: 'Консультирование проводится в режиме онлайн с использованием любых удобных вам средств. Онлайн консультирование позволяет оперативно решить возникшую у вас проблему непосредственно у вас на компьютере, при этом нет разницы в каком месте вы находитесь и соответственно для вас нет временных затрат и рисков на выезд к вам специалиста.',
    helpConfig: 'Изучив возникшую потребность и учитывая специфику вашего бизнеса, мы можем дать вам ценные рекомендации по выбору и внедрению конфигурации 1С.  Также мы можем помочь вам с интеграцией конфигураций 1С и сторонним программным обеспечением. Правильный выбор конфигурации программ и оборудования позволит избавиться от лишних ненужных трат и оптимально построить план автоматизации.',
    implementSelectedSolutions: 'Помощь при составлении дорожной карты внедрения. Для сложных проектов мы разрабатываем план проекта внедрения и доработки конфигураций. Проекты, продуманные в самом начале, имеют большие шансы на успешное завершение и удобны в эксплуатации.',
    ourConsultation: 'Наша консультации и обучение не пройдут для ваших сотрудников бесследно. В зависимости от потребности мы можем оказывать как разовые консультации для отдельных сотрудников, так и комплексное обучение группы сотрудников с индивидуальной программой. В результате ваши сотрудники приобретают знания и мотивацию.',
    ProperlySelected: 'Результатом совместной работы с нашей компанией является правильно выбранное программное обеспечение, полностью соответствующее поставленным целям. Как следствие, работа с ним будет приносить вам комфорт и радость. Наши знания помогут вам избежать частых ошибок, которые могут возникать при недостатке необходимого опыта внедрения.',
    DesignedDesignDocumentation: 'Правильно оформленная проектная документация необходима для фиксации результата работ по внедрению программного обеспечения и «извлеченных уроков», выученных при реализации сложных проектов. Документация необходима на всех этапах жизненного цикла проекта и программного обеспечения. Для небольших проектов достаточно инструкций, но наличие их крайне желательно.',
    connect: 'Подключайтесь и работайте в «1С» через интернет.',
    renting1: 'Автоматическая ежедневная архивация ваших данных без необходимости отслеживания процесса. Вам не придется волноваться о потере данных. Мы гарантируем оперативное восстановление данных из архивных копий.',
    renting2: 'Обновление стандартных конфигураций в автоматическом режиме без дополнительных затрат. Нет необходимости искать специалистов для обновления и сопровождения. Сопровождение и доработка будет проводится еще быстрее и легче.',
    renting3: 'Данные защищены профессионалами в соответствии с самыми высокими требованиями в области защиты информации. Сервера, на которых располагается информация, должным образом защищены и специализированы.'
  }
}
